Repository fenndragon/HardLight, pull requests merged in 2025-05, with the labels that each got.

#2 Weapon overhaul damage reversion
  Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/energy.yml
  Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/hitscan.yml
  Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/pistol.yml
  Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/rifle.yml
  Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/shotgun.yml
  Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Rifles/rifles.yml
  Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Rifles/rifles_assault.yml
  Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/SMGs/smgs.yml
  Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml
Labels: S: Untriaged, size/M

#11 fixed standing speed not resetting
  Content.Shared/Standing/StandingStateSystem.cs
Labels: S: Untriaged, size/XS

#13 fix map file
  Resources/Prototypes/Maps/core.yml
  Resources/Prototypes/_NF/Maps/Outpost/frontier.yml
  Resources/Textures/_HL/Logo/icon/icon-256x256.png
Labels: S: Untriaged, size/S

#17 fixed rules
  Resources/Prototypes/_NF/Guidebook/rules.yml
Labels: S: Untriaged, size/S

#24 Locker fills for station
  Resources/Prototypes/Entities/Structures/Wallmounts/Signs/posters.yml
  Resources/Prototypes/_HL/Catalog/Fills/Lockers/medical.yml
  Resources/Textures/Structures/Wallmounts/posters.rsi/poster34_legit.png
Labels: S: Untriaged, size/S

#25 Update frontier.yml
  Resources/Prototypes/_NF/Maps/Outpost/frontier.yml
Labels: S: Untriaged, size/XS

#27 changed two .yaml files
  Resources/Prototypes/Maps/core.yml
  Resources/Prototypes/Roles/Jobs/Civilian/musician.yml
Labels: S: Untriaged, size/XS

#23 MACHINE TURN BACK NOW
  Resources/Prototypes/_NF/Catalog/Fills/Backpacks/npc_loot_silicons.yml
  Resources/Prototypes/_NF/Entities/Mobs/NPCs/mob_hostile_rogue_ai.yml
Labels: S: Untriaged, size/M

#30 removing access groups
  Resources/Prototypes/Roles/Jobs/Cargo/cargo_technician.yml
  Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
  Resources/Prototypes/Roles/Jobs/Civilian/clown.yml
  Resources/Prototypes/Roles/Jobs/Civilian/lawyer.yml
  Resources/Prototypes/Roles/Jobs/Civilian/librarian.yml
  Resources/Prototypes/Roles/Jobs/Civilian/mime.yml
  Resources/Prototypes/Roles/Jobs/Civilian/musician.yml
  Resources/Prototypes/Roles/Jobs/Wildcards/boxer.yml
  Resources/Prototypes/Roles/Jobs/Wildcards/psychologist.yml
  Resources/Prototypes/Roles/Jobs/Wildcards/zookeeper.yml
Labels: S: Untriaged, size/S

#32 Re-adds mosquito and stalker with fixes
  Resources/Maps/_HL/Shuttles/ColSec/mosquito.yml
  Resources/Maps/_HL/Shuttles/ColSec/stalker.yml
  Resources/Prototypes/_HL/Shipyard/ColSec/mosquito.yml
  Resources/Prototypes/_HL/Shipyard/ColSec/stalker.yml
Labels: S: Untriaged, size/XL

#33 this was the wrong ID
  Resources/Prototypes/Guidebook/rules.yml
  Resources/Prototypes/_NF/Catalog/Fills/Backpacks/npc_loot_silicons.yml
Labels: S: Untriaged, size/XS

#35 GUN CHANGES THE FOURTH
  Resources/Prototypes/_NF/Catalog/Fills/Items/weapon_cases_expedition.yml
  Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/base_bullets.yml
  Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/pistol.yml
  Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/rifle.yml
  Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/shotgun.yml
  Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/Pistols/base_pistol.yml
  Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/SMGs/base_smg.yml
  Resources/Prototypes/_NF/Entities/Objects/Weapons/Guns/expedition_guns.yml
Labels: S: Untriaged, size/M

#42 cargo restock crate values
  Resources/Prototypes/Catalog/Cargo/cargo_vending.yml
Labels: S: Untriaged, size/S

#43 Id comp pass
  Content.Shared/Access/Components/IdCardConsoleComponent.cs
  Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
  Resources/Prototypes/Roles/Jobs/departments.yml
Labels: S: Untriaged, size/M

#45 Id comp pass
  Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
  Resources/Prototypes/Roles/Jobs/departments.yml
  Resources/Prototypes/_HL/Roles/Jobs/departments.yml
Labels: S: Untriaged, size/M

#36 Spraypaint
  Content.Client/Paint/PaintVisualizerSystem.cs
  Content.Server/Paint/PaintSystem.cs
  Content.Server/Storage/EntitySystems/SpawnItemsOnUseSystem.cs
  Content.Shared/Paint/PaintComponent.cs
  Content.Shared/Paint/PaintDoAfterEvent.cs
  Content.Shared/Paint/PaintRemoverComponent.cs
  Content.Shared/Paint/PaintRemoverDoAfterEvent.cs
  Content.Shared/Paint/PaintRemoverSystem.cs
  Content.Shared/Paint/PaintedComponent.cs
  Content.Shared/Paint/SharedPaintSystem.cs
  Content.Shared/SprayPainter/SharedSprayPainterSystem.cs
  Resources/Locale/en-US/paint/paint.ftl
  Resources/Prototypes/Catalog/Cargo/cargo_fun.yml
  Resources/Prototypes/Catalog/Fills/Crates/fun.yml
  Resources/Prototypes/Catalog/Fills/Lockers/misc.yml
  Resources/Prototypes/Entities/Mobs/NPCs/carp.yml
  Resources/Prototypes/Entities/Mobs/NPCs/revenant.yml
  Resources/Prototypes/Entities/Mobs/Player/guardian.yml
  Resources/Prototypes/Entities/Objects/Fun/spray_paint.yml
  Resources/Prototypes/Entities/Objects/Materials/Sheets/glass.yml
  Resources/Prototypes/Entities/Objects/Materials/Sheets/metal.yml
  Resources/Prototypes/Entities/Objects/Materials/Sheets/other.yml
  Resources/Prototypes/Entities/Objects/Materials/materials.yml
  Resources/Prototypes/Entities/Objects/Misc/tiles.yml
  Resources/Prototypes/Entities/Objects/Specific/Janitorial/soap.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/e_sword.yml
  Resources/Prototypes/Entities/Structures/Decoration/bonfire.yml
  Resources/Prototypes/Entities/Structures/Holographic/projections.yml
  Resources/Prototypes/Entities/Structures/Machines/Computers/base_structurecomputers.yml
  Resources/Prototypes/Entities/Structures/Machines/base_structuremachines.yml
  Resources/Prototypes/tags.yml
  Resources/Textures/Interface/VerbIcons/paint.svg
  Resources/Textures/Interface/VerbIcons/paint.svg.192dpi.png
  Resources/Textures/Interface/VerbIcons/paint.svg.192dpi.png.yml
  Resources/Textures/Objects/Fun/spraycans.rsi/clown-inhand-left.png
  Resources/Textures/Objects/Fun/spraycans.rsi/clown-inhand-right.png
  Resources/Textures/Objects/Fun/spraycans.rsi/meta.json
  Resources/Textures/Objects/Fun/spraycans.rsi/spray-inhand-left.png
  Resources/Textures/Objects/Fun/spraycans.rsi/spray-inhand-right.png
  Resources/Textures/Objects/Fun/spraycans.rsi/spray_cap.png
Labels: S: Untriaged, size/M

#47 Vandanna
  Resources/Locale/en-US/_NF/store/uplink-catalog.ftl
  Resources/Prototypes/Access/misc.yml
  Resources/Prototypes/_NF/Catalog/mercenary_uplink_catalog.yml
  Resources/Prototypes/_NF/Entities/Objects/Specific/mercenary.yml
  Resources/Prototypes/_NF/Roles/Jobs/Civilian/mercenary.yml
Labels: S: Untriaged, size/S

#48 Headsets id fills new
  Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml
  Resources/Prototypes/Roles/Jobs/Command/captain.yml
  Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
  Resources/Prototypes/_HL/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/_HL/Entities/Clothing/Ears/headsets.yml
Labels: S: Untriaged, size/S

#50 Merccoins
  Content.Shared/_NF/CCVar/NFCCVars.cs
  Resources/Prototypes/_NF/Catalog/Fills/Backpacks/npc_loot_cultists.yml
  Resources/Prototypes/_NF/Catalog/Fills/Backpacks/npc_loot_explorers.yml
  Resources/Prototypes/_NF/Catalog/Fills/Backpacks/npc_loot_mercenaries.yml
  Resources/Prototypes/_NF/Catalog/Fills/Backpacks/npc_loot_punks.yml
  Resources/Prototypes/_NF/Catalog/Fills/Backpacks/npc_loot_silicons.yml
  Resources/Prototypes/_NF/Catalog/Fills/Backpacks/npc_loot_syndicate.yml
Labels: S: Untriaged, size/M

#53 Copied Decals for Ease of Mapping.
  Resources/Textures/_HL/Effects/crayondecals.rsi/LetterA.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/LetterB.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/LetterC.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/LetterD.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/LetterE.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/LetterF.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/LetterG.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/LetterH.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/LetterI.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/LetterJ.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/LetterK.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/LetterL.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/LetterM.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/LetterN.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/LetterO.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/LetterP.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/LetterQ.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/LetterR.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/LetterS.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/LetterT.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/LetterU.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/LetterV.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/LetterW.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/LetterX.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/LetterY.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/LetterZ.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/Number0.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/Number1.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/Number2.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/Number3.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/Number4.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/Number5.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/Number6.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/Number7.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/Number8.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/Number9.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/PunctAmpersand.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/PunctChevron.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/PunctComma.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/PunctDot.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/PunctEquals.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/PunctExclamationmark.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/PunctHeart.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/PunctMinus.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/PunctPercent.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/PunctPlus.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/PunctPound.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/PunctQuestionmark.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/PunctStar.png
  Resources/Textures/_HL/Effects/crayondecals.rsi/meta.json
Labels: S: Untriaged, size/XS
